---
title: "elasticnet"
output:
  bookdown::html_document2:
    fig.width: 18
    fig.height: 8
---

```{r elasticnet_setup, message = FALSE}
library("targets")
library("ameld")
library("viridisLite")
tar_load(arcvob)
tar_load(bootrcv)
tar_load(bootrcvcc)
tar_load(bootarcv)
tar_load(bootrcv.woIC)
tar_load(amelddata)
tar_load(amelddatacc)
tar_load(ameldcfg)
tar_load(zlog_data)
tar_load(zlog_data_complete_cases)
```

# Tuning alpha

```{r arcvob}
arcvob
```

```{r arcvob-plot-alpha}
plot(arcvob)
```

```{r arcvob-plot-lambdamin}
plot(arcvob, what = "lambda.min")
```

```{r arcvob-plot-lambda1se}
plot(arcvob, what = "lambda.1se")
```

# Bootstrapping

## rcv.glmnet

```{r bootrcv}
plot(bootrcv, what = "calibration")

ps <- lapply(
    zlog_data[paste0("SurvProbMeld", c("Unos", "NaUnos", "3", "Plus7"))],
    function(p) {
        ctpnts <- cutpoints(p, n = ameldcfg$m)
        f <- cut(p, ctpnts, include.lowest = TRUE)
        list(
            predicted = groupmean(p, f = f),
            observed = observed_survival(
                amelddata$y, f = f, times = ameldcfg$times
            )
        )
    }
)
names(ps) <- c("MELD", "MELD-Na", "MELD 3.0", "MELD-Plus7")
col <- viridisLite::viridis(7)[4:7]

for (i in seq_along(ps)) {
    lines(
        ps[[i]]$predicted, ps[[i]]$observed, col = col[i], type = "b", pch = 19
    )
}
legend("topleft", col = col, legend = names(ps), pch = 19, bty = "n")

plot(bootrcv, what = "selected", cex = 0.5)
plot(bootrcv$fit, what = "path", xvar = "norm", nlabel = 14, cex.lab = 0.5)
plot(bootrcv$fit, what = "path", xvar = "lambda", nlabel = 14, cex.lab = 0.5)
plot(bootrcv$fit, what = "path", xvar = "dev", nlabel = 14, cex.lab = 0.5)
```

## rcv.glmnet (complete cases only)

```{r bootrcvcc}
plot(bootrcvcc, what = "calibration")

ps <- lapply(
    zlog_data_complete_cases[paste0("SurvProbMeld", c("Unos", "NaUnos", "3", "Plus7"))],
    function(p) {
        ctpnts <- cutpoints(p, n = ameldcfg$m)
        f <- cut(p, ctpnts, include.lowest = TRUE)
        list(
            predicted = groupmean(p, f = f),
            observed = observed_survival(
                amelddatacc$y, f = f, times = ameldcfg$times
            )
        )
    }
)
names(ps) <- c("MELD", "MELD-Na", "MELD 3.0", "MELD-Plus7")
col <- viridisLite::viridis(7)[4:7]

for (i in seq_along(ps)) {
    lines(
        ps[[i]]$predicted, ps[[i]]$observed, col = col[i], type = "b", pch = 19
    )
}
legend("topleft", col = col, legend = names(ps), pch = 19, bty = "n")

plot(bootrcvcc, what = "selected", cex = 0.5)
plot(bootrcvcc$fit, what = "path", xvar = "norm", nlabel = 14, cex.lab = 0.5)
plot(bootrcvcc$fit, what = "path", xvar = "lambda", nlabel = 14, cex.lab = 0.5)
plot(bootrcvcc$fit, what = "path", xvar = "dev", nlabel = 14, cex.lab = 0.5)
```

## bootrcv.woIC

Exclude IL-6 and CYSC columns from the data set.

```{r bootrcv.woIC}
plot(bootrcv.woIC, what = "calibration")
plot(bootrcv.woIC, what = "selected", cex = 0.5)
```

## arcv.glmnet

```{r bootarcv}
a <- c(table(sapply(bootarcv$models, function(m)m$fit$alpha)))
plot(bootarcv, what = "calibration")
```
```{r bootarcv2, fig.height = 12}
plot(bootarcv, what = "selected")
plot_dots(a, main = "Selected Alpha Values")
```
