---
title: "Histograms"
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

```{r histograms_setup, message = FALSE}
library("targets")
library("beeswarm")
library("viridisLite")
tar_load(imp_data)
tar_load(zlog_data)

.hist <- function(
    ..., xlab = deparse(substitute(x)), main = paste("Histogram of", xlab),
    col = palette.colors(2L)[2L]
)hist(..., main = main, xlab = xlab, col = col)

.qqnorm <- function(y, ..., yname = deparse(substitute(y)),
    ylab = paste0("Sample Quantiles (", yname, ")"),
    col = palette.colors(2L)[2L]) {
    qqnorm(y, ..., ylab = ylab, col = col, pch = 19L)
    qqline(y, ..., col = col)
}

.bp <- function(x, formula, col = cividis(ncol(x)), main = NULL,
                outline = FALSE) {
    boxplot(
        formula, data = x, col = gsub("..$", "40", col),
        pch = NA, outline = outline,
        main = main
    )
    beeswarm(formula, data = x, col = col, add = TRUE, pch = 19L)
}
```

# Age

```{r histograms_age}
.hist(imp_data$Age, xlab = "Age")
```

# Raw Data (imputed)

```{r histograms_labs, results = "asis", message = FALSE, warning = FALSE}
labv <- sort(grep("_[SECQ]$", colnames(imp_data), value = TRUE))

for (v in labv) {
    cat("\n\n##", v , "\n\n")
    .hist(imp_data[[v]], main = paste0("Histogram of ", v), xlab = v)
    .qqnorm(imp_data[[v]], yname = v)
}
```

# Zlog Data (imputed)

```{r histograms_labs_zlog, results = "asis", message = FALSE, warning = FALSE}
for (v in labv) {
    cat("\n\n##", v , "\n\n")
    .hist(zlog_data[[v]], main = paste0("Histogram of ", v), xlab = v)
    .qqnorm(zlog_data[[v]], yname = v)
}
```

# Raw vs Zlog Data

## Compare Sexes

```{r histograms_rvsz_sex, results = "asis", fig.width = 12, fig.height = 12}
old.par <- par(no.readonly = TRUE)
par(mfrow = c(1L, 2L))
log_data <- imp_data
log_data[labv] <- lapply(log_data[labv], log)
col <- cividis(2L)
for (v in labv) {
    cat('\n\n### ', v, '\n\n')
    fm <- as.formula(paste0(v, " ~ Sex"))
    .bp(log_data, fm, col = col, main = "log()")
    .bp(zlog_data, fm, col = col, main = "zlog()")
}
par(old.par)
```

## Compare Status

```{r histograms_rvsz_status, results = "asis", fig.width = 12, fig.height = 12}
old.par <- par(no.readonly = TRUE)
par(mfrow = c(1L, 2L))
for (v in labv) {
    cat('\n\n### ', v, '\n\n')
    fm <- as.formula(paste0(v, " ~ Deceased"))
    .bp(log_data, fm, col = col, main = "log()")
    .bp(zlog_data, fm, col = col, main = "zlog()")
}
par(old.par)
```

## Compare Sexes : Status

```{r histograms_rvsz_sex_status, results = "asis", fig.width = 12, fig.height = 12}
old.par <- par(no.readonly = TRUE)
par(mfrow = c(1L, 2L))
col <- cividis(4L)
for (v in labv) {
    cat('\n\n### ', v, '\n\n')
    fm <- as.formula(paste0(v, " ~ Sex + Deceased"))
    .bp(log_data, fm, col = col, main = "log()")
    .bp(zlog_data, fm, col = col, main = "zlog()")
}
par(old.par)
```
