---
title: "A new machine-learning-based prediction of survival in patients with end-stage liver disease"
subtitle: >
    Supplement
author:
    - Sebastian Gibb^[mail@sebastiangibb.de]
    - Thomas Berg
    - Adam Herber
    - Berend Isermann
    - Thorsten Kaiser
bibliography:
  - "`r rprojroot::find_rstudio_root_file('analysis', 'bibliography', 'bibliography.bib')`"
output:
  bookdown::html_document2:
    toc: false
  bookdown::word_document2:
    keep_md: true
    pandoc_args: # pandoc_args doesn't support r evaluation
      - --csl=pandoc/csl/vancouver.csl
---

```{r knitr_setup, include = FALSE}
```

```{r knitr_setup_word, eval = !knitr::is_html_output(), include = FALSE}
knitr::opts_chunk$set(dpi = 1200, echo = FALSE)
```

```{r supplement_setup, echo = FALSE, message = FALSE}
library("ameld")
library("data.table")
library("targets")
library("mlr3")
library("mlr3misc")
library("mlr3proba")
library("mlr3viz")
library("viridis")
library("ggplot2")
```

# Survival plot

```{r survival.plot, fig.cap = "Survival plot. Kaplan-Meier survival estimate for the first 90 days of the analyzed population.", fig.width = 8, fig.height = 5}
tar_load(zlog_data)
srv <- Surv(zlog_data$DaysAtRisk, zlog_data$Deceased)
col <- palette.colors(nlevels(zlog_data$MeldCategory))

srvfit <- survfit(srv ~ 1)
times <- c(2, 7, 14, 30, 90)

## calculate risk tables
sm <- summary(srvfit, times = times)
nrisk <- as.matrix(sm$n.risk)
ncumevents <- as.matrix(cumsum(sm$n.event))
rownames(nrisk) <- rownames(ncumevents) <- times

## keep old graphic parameters and restore them afterwards
old.par <- par(no.readonly = TRUE)

layout(matrix(1:3, nrow = 3), height = c(5, 1, 1))
plot_surv(
    srvfit,
    main = "Kaplan-Meier survival estimate to day 90",
    times = times,
    xmax = 90,
    col = col[2],
    cex = 1.2
)
par(mar = c(1.1, 5.1, 1.1, 2.1))
plot_table(
    nrisk, at = times, main = "Number at risk",
    xaxis = FALSE, cex.text = 1, ylabels = FALSE
)
par(mar = c(1.1, 5.1, 1.1, 2.1))
plot_table(
    ncumevents, at = times, main = "Cumulative number of events",
    xaxis = FALSE, cex.text = 1, ylabels = FALSE
)
par(old.par)
```

# Benchmark results of machine-learning algorithms

```{r benchmark-plot, fig.cap = "Benchmark results of machine-learning algorithms.", echo = FALSE, fig.width = 18, fig.height = 12}
tar_load(bmrk_results)
r <- bmrk_results$clone()
id <- grep("^scale", x = r$learners$learner_id, invert = TRUE, value = TRUE)
r$filter(task_id = "zlog_eldd", learner_id = id)

relabel_learners <- function(x) {
    x <- gsub("\\.tuned", "", x)
    x <- gsub("1$", "", x)
    x <- gsub("^surv\\.", "", x)
    x
}

## taken from mlr3viz::autoplot.BenchmarkResults
task <- r$tasks$task[[1L]]
measure <- mlr3::assert_measure(mlr3::as_measure(msr("surv.cindex"), task_type = task$task_type), task = task)
measure_id <- measure$id
tab <- fortify(r, measure = measure)
tab$nr <- sprintf("%09d", tab$nr)
tab$learner_id <- relabel_learners(tab$learner_id)
tab$group <- tab$learner_id
tab$group[tab$group == "xgboost"] <- "boosting"
tab$group[grepl("lasso|ridge|net", tab$group)] <- "penalized regression"
tab$group[grepl("svm", tab$group)] <- "svm"
tab$group[tab$group %in% c("ranger", "rfsrc")] <- "random forests"
tab$group[tab$group %in% c("coxtime", "deepsurv")] <- "neural networks"
tab$group <- factor(
    tab$group,
    levels = c(
        "cox", "penalized regression",
        "random forests", "boosting", "svm", "neural networks"
    )
)
learner_label_map <- tab[!duplicated(tab$nr), c("nr", "learner_id")]
learner_labels <- learner_label_map$learner_id
names(learner_labels) <- learner_label_map$nr
ggplot(tab, mapping = aes(x = .data$nr, y = .data[[measure_id]])) +
    geom_boxplot(aes(fill = .data$group)) +
    labs(fill = "Algorithm category") +
    labs(y = "Harrell's concordance index") +
    labs(x = "Model") +
    scale_x_discrete(labels = learner_labels) +
    scale_fill_viridis(labels = learner_labels, discrete = TRUE, option = "cividis") +
    facet_grid(cols = vars(group), scales = "free_x", space = "free") +
    mlr3viz:::apply_theme(list(theme_mlr3())) +
    geom_jitter(position = position_jitter(0.2)) +
    theme(
        legend.position = "none",
        strip.text.x = element_text(size = 20),
        text = element_text(size = 24),
        axis.text.x = element_text(angle = 45, hjust = 1)
    )
```

```{r benchmark-table, echo = FALSE}
agg <- bmrk_results$aggregate(msr("surv.cindex", id = "harrell"))
agg[, `:=`
    (nr = NULL, resample_result = NULL, resampling_id = NULL, iters = NULL)
]
agg <- subset(agg, task_id == "zlog_eldd" & !grepl("^scale", learner_id))
agg[, task_id := NULL]
setorder(agg, -harrell)
agg$name <- relabel_learners(agg$learner_id)
knitr::kable(
    agg[, list(name, harrell)],
    col.names = c("Model", "Harrell's concordance index"),
    caption = paste0("Benchmark results. Ranking of the ", nrow(agg), " tested machine-learning algorithms."),
    digits = 3
)
```

# Observed versus MELD-Na-expected 90-day mortality

```{r tbl-observed-vs-expected-mortality5, results = "asis", echo = FALSE, message = FALSE}
## identical to table in article.Rmd but categories spanning just 5 points
tar_load(labelled_meld_data)

## MELD mortality values are taken from @vanderwerken2021
vanderwerken <- data.frame(
    MELD = 6:40,
    mortality = 1 -
    c(0.9700, 0.9720, 0.9715, 0.9744, 0.9802, 0.9759, 0.9747, 0.9791,
      0.9752, 0.9651, 0.9606, 0.9514, 0.9380, 0.9309, 0.9128, 0.9048,
      0.8721, 0.8509, 0.8098, 0.7869, 0.7406, 0.6787, 0.6619, 0.5791,
      0.5244, 0.4906, 0.4831, 0.4069, 0.3860, 0.3629, 0.2944, 0.2429,
      0.2469, 0.1003, 0.1562)
)

breaks <- c(-Inf, seq(10, 40, by=5), Inf)
labels <- c(
    paste0(
        "[",
        floor(min(labelled_meld_data$ScoreMeldNaUnos, na.rm = TRUE)),
        ",9]"
    ),
    paste0("[", seq(10, 35, by=5), ",", seq(15, 40, by=5), ")"),
    paste0(
        "[40,",
        ceiling(max(labelled_meld_data$ScoreMeldNaUnos, na.rm = TRUE)),
        ")"
    )
)

vanderwerken$MeldCategory <- cut(
    vanderwerken$MELD,
    breaks = breaks,
    labels = labels,
    right = FALSE
)
expected <- tapply(
    vanderwerken$mortality, vanderwerken$MeldCategory, mean
)

tbl_observed_vs_expected_mortality5 <- observed_vs_expected_mortality(
    Surv(labelled_meld_data$DaysAtRisk, labelled_meld_data$Deceased),
    f = cut(
        labelled_meld_data$ScoreMeldNaUnos,
        breaks = breaks, labels = labels,
        right = FALSE
    ),
    time = 90, expected
)

tbl_observed_vs_expected_mortality5$ObservedMortality <-
    tbl_observed_vs_expected_mortality5$ObservedMortality * 100
tbl_observed_vs_expected_mortality5$ExpectedMortality <-
    tbl_observed_vs_expected_mortality5$ExpectedMortality * 100
knitr::kable(
    cbind(
        row.names(tbl_observed_vs_expected_mortality5),
        tbl_observed_vs_expected_mortality5
    ),
    row.names = FALSE,
    col.names =
        c(
            "MELD category",
            "Observed deaths (n)",
            "Expected deaths (n)",
            "Standardized mortality ratio (SMR)",
            "Observed mortality (%)",
            "Expected mortality (%)"
        ),
    caption = paste0(
        "Observed vs. MELD-Na-expected 90-day mortality. ",
        "MELD-Na mortality values are taken from @vanderwerken2021 and ",
        "the mean value was calculated for each MELD-Na category.",
        "All patients censored before day 90 are ignored for ",
        "the calculation of the MELD-Na-expected deaths. ",
        "SMR, Standardized mortality ratio = observed deaths/expected deaths."
    ),
    digits = 1
)
```

# AUROC trend

```{r roc-plot, echo = FALSE, fig.width = 18, fig.height = 12, fig.cap = "Trend in the area under the time-dependent receiver operating characteristic curve (AUROC) based on the nonparametric inverse probability of censoring weighting estimate (IPCW) for AMELD, MELD, MELD-Na, MELD 3.0 and MELD-Plus7, as described in [@blanche2013]."}
tar_load(timeROC_MELD)
tar_load(timeROC_MELDNa)
tar_load(timeROC_MELD3)
tar_load(timeROC_MELDPlus7)
tar_load(timeROC_RCV)

m <- list(
    AMELD = timeROC_RCV,
    MELD = timeROC_MELD,
    "MELD-Na" = timeROC_MELDNa,
    "MELD 3.0" = timeROC_MELD3,
    "MELD-Plus7" = timeROC_MELDPlus7
)
plot_surv_roc_trend(m, xlab = "time [days]", col = viridisLite::viridis(6)[-2])
```

```{r roc-plot-wo-cb, echo = FALSE, fig.width = 18, fig.height = 12, fig.cap = "Trend in the area under the time-dependent receiver operating characteristic curve (AUROC) based on the nonparametric inverse probability of censoring weighting estimate (IPCW) for AMELD, MELD, MELD-Na, MELD 3.0 and MELD-Plus7, as described in [@blanche2013]. Identical to the figure above but without confidence bands."}
m <- lapply(m, function(x) { x$confint <- NULL;x })
plot_surv_roc_trend(m, xlab = "time [days]", col = viridisLite::viridis(6)[-2])
```

# Variable importance

```{r vimpbs, fig.width = 8, fig.height = 10, fig.cap = "Variable importance by frequency of bootstrap selections.", echo = FALSE, message = FALSE}
tar_load(bootrcv)
plot(bootrcv, what = "selected", cex = 0.5)
```

```{r vimprf, fig.width = 8, fig.height = 10, fig.cap = "Variable importance by logrank in random forest.", echo = FALSE, message = FALSE}
tar_load(rngr)
plot_dots(
    sort(rngr$variable.importance),
    main = "Variable importance (random forest)",
    xlab = rngr$splitrule
)
```

# References
