---
title: "Survival Plots"
output:
  bookdown::html_document2:
    fig.width: 12
    fig.height: 8
---

```{r survplots_setup, message = FALSE}
library("targets")
library("ameld")
library("survival")
tar_load(zlog_data)

srv <- Surv(zlog_data$DaysAtRisk, zlog_data$Deceased)
col <- palette.colors(nlevels(zlog_data$MeldCategory))
```

# Survival

```{r survplots_total}
srvfit <- survfit(srv ~ 1)
plot_surv(
    srvfit,
    main = "Kaplan-Meier Survival Estimate",
    col = col[2]
)
```

```{r survplots_90d}
times <- c(0, 7, 14, 30, 60, 90)

## calculate risk tables
sm <- summary(srvfit, times = times)
nrisk <- as.matrix(sm$n.risk)
ncumevents <- as.matrix(cumsum(sm$n.event))
rownames(nrisk) <- rownames(ncumevents) <- times

## keep old graphic parameters and restore them afterwards
old.par <- par(no.readonly = TRUE)

layout(matrix(1:3, nrow = 3), height = c(5, 1.5, 1.5))
plot_surv(
    srvfit,
    main = "Kaplan-Meier Survival Estimate to day 90",
    times = times,
    xmax = 90,
    col = col[2]
)
par(mar = c(5.1, 5.1, 1.1, 2.1))
plot_table(
    nrisk, at = times, main = "Number at risk",
    xaxis = FALSE, cex.text = 1.5, ylabels = FALSE
)
par(mar = c(5.1, 5.1, 1.1, 2.1))
plot_table(
    ncumevents, at = times, main = "Cumulative number of events",
    xaxis = FALSE, cex.text = 1.5, ylabels = FALSE
)
par(old.par)
```

# Survival vs MELD Category

```{r survplots_meld_total}
srvfit <- survfit(srv ~ MeldCategory, data = zlog_data)
col <- rev(col)
plot_surv(
    srvfit,
    main = "Kaplan-Meier Survival Estimate",
    col = col
)
legend(
    "bottomright",
    legend = levels(zlog_data$MeldCategory),
    col = col, lwd = 1, pch = 3, bty = "n"
)
```

```{r survplots_meld_90d, fig.width = 12, fig.height = 12}
## calculate risk tables
sm <- summary(srvfit, times = times)
ncumevents <- nrisk <- matrix(
    NA_real_,
    nrow = length(times), ncol = nlevels(zlog_data$MeldCategory),
    dimnames = list(times, levels(zlog_data$MeldCategory))
)
nrisk[][seq_along(sm$n.risk)] <- sm$n.risk
ncumevents[][seq_along(sm$n.event)] <- sm$n.event
ncumevents <- apply(ncumevents, MARGIN = 2, cumsum)

## keep old graphic parameters and restore them afterwards
old.par <- par(no.readonly = TRUE)

layout(matrix(1:3, nrow = 3), height = c(5, 2, 2))
par(mar = c(5.1, 4.1, 1.1, 2.1))
plot_surv(
    srvfit,
    main = "Kaplan-Meier Survival Estimate to day 90",
    times = times,
    xmax = 90,
    col = col
)
legend(
    "bottomright",
    legend = levels(zlog_data$MeldCategory),
    col = col, lwd = 1, pch = 3, bty = "n"
)
par(mar = c(5.1, 5.1, 1.1, 2.1))
plot_table(
    nrisk, at = times, main = "Number at risk",
    xaxis = FALSE, cex.text = 1.5, col = col
)
par(mar = c(5.1, 5.1, 1.1, 2.1))
plot_table(
    ncumevents, at = times, main = "Cumulative number of events",
    xaxis = FALSE, cex.text = 1.5, col = col
)
par(old.par)
```
