---
title: "Tables"
---

<script>
$(document).ready(function(){
    $('[data-toggle="popover"]').popover();
});

</script>

```{r histograms_setup, message = FALSE}
library("targets")
library("skimr")
library("zlog")
tar_load(raw_data)
tar_load(imp_data)
tar_load(zlog_data)
```

# Raw Data

```{r tables_skim_raw}
skim(raw_data)
```

# Raw Data (imputed)

```{r tables_skim_imp}
skim(imp_data)
```

# Zlog Data

```{r tables_skim_zlog}
skim(zlog_data)
```

# Raw Data (imputed) with Zlog Colors

```{r tables_raw_zlog, results = "asis", echo = FALSE, message = FALSE}
k <- kableExtra::kable_classic(
    kableExtra::kbl(
        imp_data,
        digits = 2,
        escape = FALSE
    ),
    "basic"
)
for (i in grep("_[CEQS]$", colnames(imp_data)))
    k <- kableExtra::column_spec(
            k, i + 1,
            background = zcol(zlog_data[[i]]),
            popover = paste0("zlog: ", round(zlog_data[[i]], 2))
    )
k |> kableExtra::scroll_box(width = "100%", height = "500px")
```

# Table One

```{r tbl1, results = "asis", echo = FALSE, message = FALSE}
library("gtsummary")
theme_gtsummary_journal(journal = "jama")
theme_gtsummary_compact()
tar_read(tbl1)
```
